from app.models import db, Animal_breed


def seed_animal_breeds():

    Dog1= Animal_breed(breed='Mixed breeds', type='dog')
    Dog2= Animal_breed(breed='Affenpinscher Hound', type='dog')
    Dog3= Animal_breed(breed='American Bulldog Terrier', type='dog')
    Dog4= Animal_breed(breed='American Pit Bull Terrier', type='dog')
    Dog5= Animal_breed(breed='Australian Cattle Dog Malamute', type='dog')
    Dog6= Animal_breed(breed='Australian Shepherd Staffordshire Terrier', type='dog')
    Dog7= Animal_breed(breed='Beagle Water Spaniel', type='dog')
    Dog8= Animal_breed(breed='Bichon Frise Cattle Dog', type='dog')
    Dog9= Animal_breed(breed='Border Collie Shepherd', type='dog')
    Dog10= Animal_breed(breed='Boston Terrier Terrier', type='dog')
    Dog11= Animal_breed(breed='Boxer', type='dog')
    Dog12= Animal_breed(breed='Chihuahua Hound', type='dog')
    Dog13= Animal_breed(breed='Cocker Spaniel', type='dog')
    Dog14= Animal_breed(breed='Corgi Collie', type='dog')
    Dog15= Animal_breed(breed='Dachshund Terrier', type='dog')
    Dog16= Animal_breed(breed='English Bulldog Mountain', type='dog')
    Dog17= Animal_breed(breed='French Bulldog Frise', type='dog')
    Dog18= Animal_breed(breed='German Shepherd', type='dog')
    Dog19= Animal_breed(breed='Golden Retriever', type='dog')
    Dog20= Animal_breed(breed='Great Dane Collie', type='dog')
    Dog21= Animal_breed(breed='Jack Russell Terrier', type='dog')
    Dog22= Animal_breed(breed='Labrador Retriever', type='dog')
    Dog23= Animal_breed(breed='Maltese Terrier', type='dog')
    Dog24= Animal_breed(breed='Pomeranian', type='dog')
    Dog25= Animal_breed(breed='Poodle', type='dog')
    Dog26= Animal_breed(breed='Pug', type='dog')
    Dog27= Animal_breed(breed='Rottweiler', type='dog')
    Dog28= Animal_breed(breed='Shih Tzu Griffon', type='dog')
    Dog29= Animal_breed(breed='Siberian Husky Terrier', type='dog')
    Dog30= Animal_breed(breed='Staffordshire Terrier', type='dog')
    Dog31= Animal_breed(breed='Yorkshire Terrier', type='dog')
    Dog32= Animal_breed(breed='Mixed breed', type='dog')
    Dog33= Animal_breed(breed='Not Listed', type='dog')

    Cat1= Animal_breed(breed='Mixed breeds', type='cat')
    Cat2= Animal_breed(breed='Abyssinian cat', type='cat')
    Cat3= Animal_breed(breed='American Shorthair Mist', type='cat')
    Cat4= Animal_breed(breed='British Shorthair', type='cat')
    Cat5= Animal_breed(breed='Burmese Cats Bobtail', type='cat')
    Cat6= Animal_breed(breed='Cicat Curl', type='cat')
    Cat7= Animal_breed(breed='Devon Rex Longhair', type='cat')
    Cat8= Animal_breed(breed='Exotic Shorthair', type='cat')
    Cat9= Animal_breed(breed='Maine Coon Cat Wirehair', type='cat')
    Cat10= Animal_breed(breed='Persian Semi-longhair', type='cat')
    Cat11= Animal_breed(breed='Ragdoll', type='cat')
    Cat12= Animal_breed(breed='Scottish Fold', type='cat')
    Cat13= Animal_breed(breed='Siamese Cats', type='cat')
    Cat14= Animal_breed(breed='Sphynx', type='cat')
    Cat15= Animal_breed(breed='Mixed breed', type='cat')
    Cat16= Animal_breed(breed='Not Listed', type='cat')


    db.session.add(Dog1)
    db.session.add(Dog2)
    db.session.add(Dog3)
    db.session.add(Dog4)
    db.session.add(Dog5)
    db.session.add(Dog6)
    db.session.add(Dog7)
    db.session.add(Dog8)
    db.session.add(Dog9)
    db.session.add(Dog10)
    db.session.add(Dog11)
    db.session.add(Dog12)
    db.session.add(Dog13)
    db.session.add(Dog14)
    db.session.add(Dog15)
    db.session.add(Dog16)
    db.session.add(Dog17)
    db.session.add(Dog18)
    db.session.add(Dog19)
    db.session.add(Dog20)
    db.session.add(Dog21)
    db.session.add(Dog22)
    db.session.add(Dog23)
    db.session.add(Dog24)
    db.session.add(Dog25)
    db.session.add(Dog26)
    db.session.add(Dog27)
    db.session.add(Dog28)
    db.session.add(Dog29)
    db.session.add(Dog30)
    db.session.add(Dog31)
    db.session.add(Dog32)
    db.session.add(Dog33)

    db.session.add(Cat1)
    db.session.add(Cat2)
    db.session.add(Cat3)
    db.session.add(Cat4)
    db.session.add(Cat5)
    db.session.add(Cat6)
    db.session.add(Cat7)
    db.session.add(Cat8)
    db.session.add(Cat9)
    db.session.add(Cat10)
    db.session.add(Cat11)
    db.session.add(Cat12)
    db.session.add(Cat13)
    db.session.add(Cat14)
    db.session.add(Cat15)
    db.session.add(Cat16)

    db.session.commit()


def undo_animal_breeds():
    db.session.execute('TRUNCATE animal_types RESTART IDENTITY CASCADE;')
    db.session.commit()